[package]
name = "sina-examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "basic_shapes"
path = "src/basic_shapes.rs"

[[bin]]
name = "text_rendering"
path = "src/text_rendering.rs"

[dependencies]
sina = { path = "../sina-core" }
